### ISSUE TITLE
quotes in schema.yml prevent more advanced usage

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#99]
it would be great if i could put calculated values into schema.yml. for example, i would love to be able to do this:

```
stripe_mrr_amortized:
  constraints:
    unique:
      - customer_id || '.' || date_day
```

that logically should work, but the whole thing gets wrapped in quotes and so it tries to interpret that entire function as a field name. here's the compiled code:

```
with validation as (
  select "customer_id || '.' || date_day" as f
  from "dbt_jthandy"."stripe_mrr_amortized"
),
validation_errors as (
    select f from validation group by f having count(*) > 1
)
select count(*) from validation_errors
```

this would be a nice thing to enable in this testing workflow; it expands the possibilities of what can be done using this pretty simple mechanism.
